version: '3.8'
services:
  api_client:
    build: ./api_client
    ports:
      - 3000:3000
  api_livre:
    build: ./api_livre
    ports:
      - 3001:3000
  api_notification:
    build: ./api_notification
    ports:
      - 3002:3000
  api_emprunt:
    build: ./api_emprunt
    ports:
      - 3003:3000
  gateway:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./gateway/default.conf:/etc/nginx/conf.d/default.conf